/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_myapplication_MainActivity */

#ifndef _Included_com_example_administrator_myapplication_ArActivity
#define _Included_com_example_administrator_myapplication_ArActivity


#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_administrator_myapplication_ArActivity_PERMISSIONS_REQUEST_CODE
#define com_example_administrator_myapplication_ArActivity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_example_administrator_myapplication_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */

JNIEXPORT jintArray JNICALL
Java_com_example_administrator_myapplication_ArActivity_Test(JNIEnv *env, jobject instance,
                                                               jlong matAddrInput,
                                                              jlong matAddrResult,
                                                               jlong matAddrResult2

);


#ifdef __cplusplus
}
#endif
#endif
